language: python
python: "3.6"
dist: xenial
compiler:
  - clang
before_script:
  - find -name clang /
  - pip install conan --upgrade
  - pip install conan_package_tools
script:
  - conan export . demo/testing
  - conan install clickhouse-cpp/0.1@demo/testing --build -pr clang
  - conan test test_package clickhouse-cpp/0.1@demo/testing
#deploy:
#  - provider: script
#    skip_cleanup: true
#    script:
#      - curl -T join_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uandreyandreevich:$BINTRAY_API_KEY "https://api.bintray.com/content/12345678/cpp_projects/join_server/$TRAVIS_BUILD_NUMBER/join_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
